services:
  - type: web
    name: myplopplop-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: COMMISSION_RATE
        value: "0.25"
      - key: FRONTEND_URL
        value: https://myplopplop.com
      - key: VAPID_PUBLIC_KEY
        value: BN1SE28WVAyfAVPaD978xZ-60fmKAIuvgne68rm3D98ygY53e1W_bLpN0pCAOdRqQLC-AiGxnPTq9EgmfcuIguc
      - key: VAPID_PRIVATE_KEY
        value: fWX1XSiB2viQdeEgbMiCMywYEBVlGNlLITERLCyNAa0
      - key: VAPID_EMAIL
        value: mailto:info@myplopplop.com
